### ISSUE TITLE
timeouts may not be set for GCS client

### ISSUE THREAD

**Issue by christopherhesse** [cshesse/blobfile#2]
The HTTP client has timeouts that may even work, but it looks like the GCS client may not have timeouts set and has no easy way to set them https://github.com/googleapis/google-cloud-python/issues/8571

**Comment by cshesse** [comment]
This may explain some of the hangs when using blobfile

**Comment by cshesse** [comment]
An alternative solution is to not use google-cloud-python and just use urllib directly to talk to the GCS JSON API: https://cloud.google.com/storage/docs/json_api/

**Comment by cshesse** [comment]
Dropped google-cloud-python and switched to urllib3, so hopefully this is fixed now.
